# Generated by Django 6.0.3 on 2026-06-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_name_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fullname',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
