# Generated by Django 6.0.3 on 2026-06-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
