# Generated by Django 6.0.4 on 2026-06-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odered_item',
            name='size',
            field=models.CharField(default='M', max_length=5),
        ),
    ]
