# Generated by Django 6.0.4 on 2026-06-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_odered_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(2, 'OrderProcessesd'), (3, 'OrderDelivered'), (4, 'OrderRejected')], default=0),
        ),
    ]
