# Generated by Django 6.0.3 on 2026-06-19 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odered_item',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='odered_item',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='delete_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Processing'), (3, 'Delivered'), (4, 'Rejected')], default=0),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.CharField(default='M', max_length=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
