# Generated by Django 6.0.3 on 2026-06-19 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_odered_item_owner_remove_odered_item_product_and_more'),
        ('products', '0003_product_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product'),
        ),
        migrations.DeleteModel(
            name='Odered_item',
        ),
    ]
