# Generated by Django 6.0.3 on 2026-06-19 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderitem_order_remove_orderitem_product_and_more'),
        ('products', '0004_products_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='products.products'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
